ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'WAREHOUSE';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'FILLING_STATION';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'HOTEL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SCHOOL';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'HOSPITAL';
