ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'FLAT';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'BUNGALOW';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'DETACHED_DUPLEX';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'SEMI_DETACHED_DUPLEX';
ALTER TYPE "PropertyType" ADD VALUE IF NOT EXISTS 'TERRACE';
