import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '../../constants';
import { Button } from '../../components/Button';
import { createService } from '../../services/services';
import { getApiErrorMessage } from '../../utils/errors';
import type { ProfessionalCategory } from '../../types';
const categories:ProfessionalCategory[]=['PLUMBER','ELECTRICIAN','TILER','BRICKLAYER','CARPENTER','PAINTER','ENGINEER','ARCHITECT','OTHER'];
export default function NewServiceScreen(){const [category,setCategory]=useState<ProfessionalCategory>('PLUMBER');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [loading,setLoading]=useState(false);const save=async()=>{if(!title.trim()||!description.trim())return Alert.alert('Missing details','Add a service title and description.');setLoading(true);try{await createService({category,title:title.trim(),description:description.trim()});Alert.alert('Service published','Your service is now available for matching.');router.back();}catch(e){Alert.alert('Could not publish',getApiErrorMessage(e,'Create a professional profile first.'));}finally{setLoading(false);}};return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Add a service</Text><Text style={styles.note}>Publish a clear service offering for customers and agents to discover.</Text><Text style={styles.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map(item=><Text key={item} onPress={()=>setCategory(item)} style={[styles.chip,category===item&&styles.selected]}>{item.replaceAll('_',' ')}</Text>)}</ScrollView><TextInput style={styles.input} placeholder="Service title" placeholderTextColor={COLORS.muted} value={title} onChangeText={setTitle}/><TextInput style={[styles.input,styles.multiline]} placeholder="Describe the work, experience and coverage" placeholderTextColor={COLORS.muted} value={description} onChangeText={setDescription} multiline/><Button label="Publish service" loading={loading} onPress={save}/></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},content:{padding:16,gap:14},title:{color:COLORS.text,fontSize:22,fontWeight:'800'},note:{color:COLORS.muted,lineHeight:19},label:{color:COLORS.text,fontWeight:'700'},chips:{gap:8},chip:{color:COLORS.text,paddingHorizontal:12,paddingVertical:9,borderRadius:16,borderWidth:1,borderColor:COLORS.border,overflow:'hidden'},selected:{color:'#fff',backgroundColor:COLORS.primary,borderColor:COLORS.primary},input:{borderWidth:1,borderColor:COLORS.border,borderRadius:10,padding:13,color:COLORS.text,backgroundColor:COLORS.surface},multiline:{minHeight:120,textAlignVertical:'top'}});
