import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '../../constants';
import { fetchRequests } from '../../services/requests';

export default function RequestsScreen() {
  const [q, setQ] = useState(''); const [type, setType] = useState<string | undefined>(); const [days, setDays] = useState<number | undefined>();
  const { data = [], isLoading } = useQuery({ queryKey: ['requests', q, type, days], queryFn: () => fetchRequests({ q: q.trim() || undefined, type, createdAfter: days ? new Date(Date.now() - days * 86400000).toISOString() : undefined }) });
  return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.title}>What people need</Text><Pressable onPress={() => router.push('/requests/new')}><Text style={styles.action}>Post a request</Text></Pressable></View><TextInput style={styles.search} value={q} onChangeText={setQ} placeholder="Search needs..." placeholderTextColor={COLORS.muted}/><ScrollView horizontal style={{flexGrow:0}} contentContainerStyle={styles.filters}>{['PROPERTY','LAND','HOUSEHOLD','PROFESSIONAL','SERVICE'].map((item) => <Text key={item} onPress={() => setType(type === item ? undefined : item)} style={[styles.filter, type === item && styles.selected]}>{item.replace('_',' ')}</Text>)}</ScrollView><ScrollView horizontal style={{flexGrow:0}} contentContainerStyle={styles.filters}>{[{label:'Any time'},{label:'Past week',days:7},{label:'Past month',days:30}].map((item) => <Text key={item.label} onPress={() => setDays(item.days)} style={[styles.filter, days === item.days && styles.selected]}>{item.label}</Text>)}</ScrollView><ScrollView contentContainerStyle={styles.list}>{isLoading && <Text style={styles.note}>Loading requests...</Text>}{!isLoading && data.length === 0 && <Text style={styles.note}>No matching requests yet.</Text>}{data.map((item) => <View key={item.id} style={styles.card}><Text style={styles.type}>{item.type.replaceAll('_', ' ')}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.description}>{item.description}</Text>{item.criteria && <Text style={styles.note}>{Object.entries(item.criteria).filter(([, value]) => value !== undefined).map(([key,value]) => `${key}: ${value}`).join(' · ')}</Text>}{item.city?.name && <Text style={styles.note}>{item.city.name}</Text>}{(item.createdBy?.phone || item.createdBy?.email) && <Pressable onPress={() => Linking.openURL(item.createdBy?.phone ? `tel:${item.createdBy.phone}` : `mailto:${item.createdBy?.email}`)}><Text style={styles.contact}>{item.createdBy?.phone || item.createdBy?.email}</Text></Pressable>}</View>)}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},header:{padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:COLORS.text,fontSize:22,fontWeight:'800'},action:{color:COLORS.primary,fontWeight:'700'},search:{marginHorizontal:16,borderWidth:1,borderColor:COLORS.border,borderRadius:10,padding:13,color:COLORS.text,backgroundColor:COLORS.surface},filters:{gap:8,padding:16,alignItems:'center'},filter:{color:COLORS.text,paddingHorizontal:12,paddingVertical:8,borderRadius:16,borderWidth:1,borderColor:COLORS.border},selected:{backgroundColor:COLORS.primary,borderColor:COLORS.primary,color:'#fff'},list:{padding:16,gap:12},card:{padding:15,borderRadius:14,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,gap:7},type:{color:COLORS.primary,fontSize:11,fontWeight:'800',textTransform:'uppercase'},cardTitle:{color:COLORS.text,fontSize:16,fontWeight:'800'},description:{color:COLORS.text,lineHeight:19},contact:{color:COLORS.primary,fontWeight:'800',paddingTop:4},note:{color:COLORS.muted,paddingVertical:8}});
