import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '../../constants';
import { Button } from '../../components/Button';
import { createRequest, UserRequestType } from '../../services/requests';
import { getApiErrorMessage } from '../../utils/errors';
const TYPES: {label:string;value:UserRequestType}[]=[{label:'Apartment or home',value:'PROPERTY'},{label:'Co-tenant',value:'CO_RENTING'},{label:'Land',value:'LAND'},{label:'Household item',value:'HOUSEHOLD'},{label:'Professional',value:'PROFESSIONAL'},{label:'Service',value:'SERVICE'}];
export default function NewRequestScreen(){const [type,setType]=useState<UserRequestType>('PROPERTY');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [budget,setBudget]=useState('');const [location,setLocation]=useState('');const [loading,setLoading]=useState(false);const save=async()=>{if(!title.trim()||!description.trim())return Alert.alert('Missing details','Describe what you need.');setLoading(true);try{await createRequest({type,title:title.trim(),description:description.trim(),budgetMax:budget?Number(budget.replace(/[^0-9.]/g,'')):undefined});Alert.alert('Request posted','Agents and providers can now discover your request.');router.back();}catch(e){Alert.alert('Could not post request',getApiErrorMessage(e,'Please try again.'));}finally{setLoading(false);}};return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Post what you need</Text><Text style={styles.note}>Tell agents and professionals what you are looking for. Keep your contact details private until you choose to connect.</Text><Text style={styles.label}>What do you need?</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.types}>{TYPES.map(item=><Text key={item.value} onPress={()=>setType(item.value)} style={[styles.type,type===item.value&&styles.selected]}>{item.label}</Text>)}</ScrollView><TextInput style={styles.input} placeholder="Short title" placeholderTextColor={COLORS.muted} value={title} onChangeText={setTitle}/><TextInput style={[styles.input,styles.multiline]} placeholder="Describe your requirements" placeholderTextColor={COLORS.muted} value={description} onChangeText={setDescription} multiline/><TextInput style={styles.input} placeholder="Preferred location" placeholderTextColor={COLORS.muted} value={location} onChangeText={setLocation}/><TextInput style={styles.input} placeholder="Maximum budget (optional)" placeholderTextColor={COLORS.muted} value={budget} onChangeText={setBudget} keyboardType="numeric"/><Button label="Post request" loading={loading} onPress={save}/></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},content:{padding:16,gap:14},title:{color:COLORS.text,fontSize:22,fontWeight:'800'},note:{color:COLORS.muted,lineHeight:19},label:{color:COLORS.text,fontWeight:'700'},types:{gap:8},type:{color:COLORS.text,paddingHorizontal:12,paddingVertical:9,borderRadius:16,borderWidth:1,borderColor:COLORS.border,overflow:'hidden'},selected:{color:'#fff',backgroundColor:COLORS.primary,borderColor:COLORS.primary},input:{borderWidth:1,borderColor:COLORS.border,borderRadius:10,padding:13,color:COLORS.text,backgroundColor:COLORS.surface},multiline:{minHeight:120,textAlignVertical:'top'}});
