import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS } from '../../constants';
import { createManagedProfessional } from '../../services/professionals';
import { Button } from '../../components/Button';
import { getApiErrorMessage } from '../../utils/errors';
import type { ProfessionalCategory } from '../../types';
const categories: ProfessionalCategory[] = ['PLUMBER','ELECTRICIAN','TILER','BRICKLAYER','CARPENTER','PAINTER','ENGINEER','ARCHITECT','SURVEYOR','OTHER'];
export default function NewProfessionalScreen() { const [category,setCategory]=useState<ProfessionalCategory>('PLUMBER'); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [bio,setBio]=useState(''); const [areas,setAreas]=useState(''); const [loading,setLoading]=useState(false); const save=async()=>{if(!name.trim()||!phone.trim())return Alert.alert('Missing details','Add a name and contact number.');setLoading(true);try{await createManagedProfessional({category,displayName:name.trim(),phone:phone.trim(),bio:bio.trim()||undefined,serviceAreas:areas.split(',').map(v=>v.trim()).filter(Boolean)});Alert.alert('Submitted','The profile was added for review.');router.replace('/professionals');}catch(e){Alert.alert('Could not save',getApiErrorMessage(e,'Please try again.'));}finally{setLoading(false);}};return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Add a professional or artisan</Text><Text style={styles.note}>You can publish this profile on someone’s behalf. Add their consent and accurate contact details.</Text><Text style={styles.label}>Category</Text><View style={styles.chips}>{categories.map(item=><Pressable key={item} onPress={()=>setCategory(item)} style={[styles.chip,category===item&&styles.active]}><Text style={[styles.chipText,category===item&&styles.activeText]}>{item.replaceAll('_',' ')}</Text></Pressable>)}</View><TextInput style={styles.input} placeholder="Name or business name" placeholderTextColor={COLORS.muted} value={name} onChangeText={setName}/><TextInput style={styles.input} placeholder="Phone or WhatsApp" placeholderTextColor={COLORS.muted} value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><TextInput style={[styles.input,styles.multiline]} placeholder="Experience and specialties" placeholderTextColor={COLORS.muted} value={bio} onChangeText={setBio} multiline/><TextInput style={styles.input} placeholder="Service areas, separated by commas" placeholderTextColor={COLORS.muted} value={areas} onChangeText={setAreas}/><Button label="Submit profile" loading={loading} onPress={save}/></ScrollView></SafeAreaView>; }
const styles=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},content:{padding:16,gap:14},title:{color:COLORS.text,fontSize:22,fontWeight:'800'},note:{color:COLORS.muted,lineHeight:19},label:{color:COLORS.text,fontWeight:'700'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:16,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface},active:{backgroundColor:COLORS.primary,borderColor:COLORS.primary},chipText:{color:COLORS.text,fontSize:12},activeText:{color:'#fff'},input:{borderWidth:1,borderColor:COLORS.border,borderRadius:10,padding:13,color:COLORS.text,backgroundColor:COLORS.surface},multiline:{minHeight:110,textAlignVertical:'top'}});
